pr feedback

diff --git a/.evg.yml b/.evg.yml
--- a/.evg.yml
+++ b/.evg.yml
@@ -120,23 +120,23 @@ functions:
           # Wait for ADB to detect the device
           adb wait-for-device
 
-          # # Wait until boot animation stops (this can take a long time!)
-          # bootanim=""
-          # failcounter=0
-          # timeout_in_sec=600
-          # until [[ "$bootanim" =~ "stopped" ]]; do
-          #   bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
-          #   if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
-          #     || "$bootanim" =~ "running" ]]; then
-          #     let "failcounter += 1"
-          #     echo "Waiting for emulator to start"
-          #     if [[ $failcounter -gt timeout_in_sec ]]; then
-          #       echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
-          #       exit 1
-          #     fi
-          #   fi
-          #   sleep 1
-          # done
+          # Wait until boot animation stops (this can take a long time!)
+          bootanim=""
+          failcounter=0
+          timeout_in_sec=600
+          until [[ "$bootanim" =~ "stopped" ]]; do
+            bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
+            if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
+              || "$bootanim" =~ "running" ]]; then
+              let "failcounter += 1"
+              echo "Waiting for emulator to start"
+              if [[ $failcounter -gt timeout_in_sec ]]; then
+                echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+                exit 1
+              fi
+            fi
+            sleep 1
+          done
 
           echo "Emulator is ready"
 
