STITCH-1466 - Implement Remote MongoDB Service in Core, Android, and Server

diff --git a/.evg.yml b/.evg.yml
--- a/.evg.yml
+++ b/.evg.yml
@@ -120,23 +120,23 @@ functions:
           # Wait for ADB to detect the device
           adb wait-for-device
 
-          # Wait until boot animation stops (this can take a long time!)
-          bootanim=""
-          failcounter=0
-          timeout_in_sec=600
-          until [[ "$bootanim" =~ "stopped" ]]; do
-            bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
-            if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
-              || "$bootanim" =~ "running" ]]; then
-              let "failcounter += 1"
-              echo "Waiting for emulator to start"
-              if [[ $failcounter -gt timeout_in_sec ]]; then
-                echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
-                exit 1
-              fi
-            fi
-            sleep 1
-          done
+          # # Wait until boot animation stops (this can take a long time!)
+          # bootanim=""
+          # failcounter=0
+          # timeout_in_sec=600
+          # until [[ "$bootanim" =~ "stopped" ]]; do
+          #   bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
+          #   if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
+          #     || "$bootanim" =~ "running" ]]; then
+          #     let "failcounter += 1"
+          #     echo "Waiting for emulator to start"
+          #     if [[ $failcounter -gt timeout_in_sec ]]; then
+          #       echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+          #       exit 1
+          #     fi
+          #   fi
+          #   sleep 1
+          # done
 
           echo "Emulator is ready"
 
@@ -153,9 +153,7 @@ functions:
           export PATH=$JAVA_HOME/bin:$PATH
           git clone https://github.com/mongodb/mongo-java-driver.git
           cd mongo-java-driver
-          # TODO: replace once branch stable
-          # git checkout embedded
-          git checkout f8291ea9df985a6931056eb13e48148d101ac9b5
+          git checkout embedded
           ./gradlew install
 
   "publish_codecov":
@@ -244,18 +242,21 @@ post:
         - "./stitch-java-sdk/core/sdk/build/test-results/test/*.xml"
         - "./stitch-java-sdk/core/admin-client/build/test-results/test/*.xml"
         - "./stitch-java-sdk/core/services/mongodb-local/build/test-results/test/*.xml"
+        - "./stitch-java-sdk/core/services/mongodb-remote/build/test-results/test/*.xml"
         - "./stitch-java-sdk/core/services/aws-s3/build/test-results/test/*.xml"
         - "./stitch-java-sdk/core/services/aws-ses/build/test-results/test/*.xml"
         - "./stitch-java-sdk/core/services/http/build/test-results/test/*.xml"
         - "./stitch-java-sdk/core/services/twilio/build/test-results/test/*.xml"
         - "./stitch-java-sdk/server/coretest/build/test-results/test/*.xml"
         - "./stitch-java-sdk/server/services/mongodb-local/build/test-results/test/*.xml"
+        - "./stitch-java-sdk/server/services/mongodb-remote/build/test-results/test/*.xml"
         - "./stitch-java-sdk/server/services/aws-s3/build/test-results/test/*.xml"
         - "./stitch-java-sdk/server/services/aws-ses/build/test-results/test/*.xml"
         - "./stitch-java-sdk/server/services/http/build/test-results/test/*.xml"
         - "./stitch-java-sdk/server/services/twilio/build/test-results/test/*.xml"
         - "./stitch-java-sdk/android/coretest/build/outputs/androidTest-results/connected/*.xml"
         - "./stitch-java-sdk/android/services/mongodb-local/build/outputs/androidTest-results/connected/*.xml"
+        - "./stitch-java-sdk/android/services/mongodb-remote/build/outputs/androidTest-results/connected/*.xml"
         - "./stitch-java-sdk/android/services/aws-s3/build/outputs/androidTest-results/connected/*.xml"
         - "./stitch-java-sdk/android/services/aws-ses/build/outputs/androidTest-results/connected/*.xml"
         - "./stitch-java-sdk/android/services/http/build/outputs/androidTest-results/connected/*.xml"
